export interface Project {
  id: string
  title: string
  description: string
  longDescription?: string
  category: 'startup' | 'hackathon' | 'freelance' | 'open-source' | 'personal' | 'professional'
  stack: string[]
  coverImage: string
  liveUrl?: string
  githubUrl?: string
  prize?: string
  featured: boolean
  /** YYYY-MM, omit for single-date events (e.g. hackathons) — use endDate only */
  startDate?: string
  /** YYYY-MM, omit if ongoing */
  endDate?: string
  isVideo?: boolean
  videoUrl?: string
  images?: string[]
}

export const PROJECTS: Project[] = [
  {
    id: 'arcy-ai',
    title: 'ARCY AI',
    description:
      'AI-powered recruitment platform that automates sourcing, screening, and outreach at scale.',
    longDescription:
      'ARCY AI replaces manual recruiting workflows with an end-to-end AI agent — from job spec to qualified candidate pipeline in hours, not weeks.',
    category: 'startup',
    stack: [
      'Monorepo',
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'NestJS',
      'PostgreSQL',
      'npm',
      'AWS RDS',
      'AWS Bedrock',
      'AWS Bedrock Agentcore',
      'AWS EC2',
      'AWS IAM',
      'AWS Route53',
      'AWS SQS',
      'AWS Elastic Cache',
      'AWS CloudWatch',
      'Redis',
      'Git',
      'GitHub',
      'Claude Code',
      'ESLint',
      'PostCSS',
      'zod',
      'React Hook Form',
      'shadcn',
      'Stripe',
      'Clerk',
      'Framer Motion',
      'Lucide React',
      'Fumadocs',
      'i18n Translation',
    ],
    coverImage: '/images/projects/arcy-ai.jpg',
    images: [
      '/images/projects/arcy-ai.jpg',
      '/images/projects/arcy-ai.jpg',
      '/images/projects/arcy-ai.jpg',
    ],
    liveUrl: 'https://arcy.ai',
    featured: true,
    startDate: '2024-01',
  },
  {
    id: 'campus-arc',
    title: 'Campus Arc',
    description: ' connecting students to events, clubs, and opportunities.',
    longDescription:
      'Campus Arc is the operating system for campus life — events, clubs, internships, and peer connections in one place.',
    category: 'professional',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Expo',
      'Express',
      'Node.js',
      'PostgreSQL',
      'Framer Motion',
      'zod',
      'ESLint',
      'Resend',
      'GSAP',
      'axios',
      'TanStack React Query',
      'Lucide React',
      'Clerk',
      'AWS S3',
      'AWS EC2',
      'PostCSS',
      'Open Campus ID SDK',
      'i18n Translation',
    ],
    coverImage: '/images/projects/campus-arc.jpg',
    images: [
      '/images/projects/campus-arc.jpg',
      '/images/projects/campus-arc.jpg',
      '/images/projects/campus-arc.jpg',
    ],
    featured: true,
    startDate: '2023-09',
  },
  {
    id: 'misyon-kripto',
    title: 'misyon.kripto',
    description:
      'Crypto education platform for Turkish retail investors entering Web3 for the first time.',
    category: 'professional',
    stack: [
      'Vite.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Prisma ORM',
      'Vercel',
      'PostCSS',
      'AWS S3',
      'Reown (WalletConnect)',
      'zod',
      'wagmi',
      'viem',
      'Resend',
      'Redux Toolkit',
      'Framer Motion',
      'Ethers.js',
      'Vercel Analytics',
      'Vercel DB',
      'Lucide React',
      'shadcn',
      'TanStack React Query',
      'TanStack React Table',
      'i18n Translation',
    ],
    coverImage: '/images/projects/misyon-kripto.jpg',
    images: [
      '/images/projects/misyon-kripto.jpg',
      '/images/projects/misyon-kripto.jpg',
      '/images/projects/misyon-kripto.jpg',
    ],
    liveUrl: 'https://misyon.com/kripto',
    featured: false,
    startDate: '2023-06',
  },
  {
    id: 'misyon-bond',
    title: 'misyon.bond',
    description:
      'Fixed-income investment product UI for Misyon Bank — bonds made accessible to everyday savers.',
    category: 'freelance',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Prisma ORM',
      'Vercel',
      'PostCSS',
      'AWS S3',
      'Reown (WalletConnect)',
      'zod',
      'wagmi',
      'viem',
      'Resend',
      'Redux Toolkit',
      'Framer Motion',
      'Ethers.js',
      'Vercel Analytics',
      'Vercel DB',
      'Lucide React',
      'shadcn',
      'TanStack React Query',
      'TanStack React Table',
      'i18n Translation',
    ],
    coverImage: '/images/projects/misyonbond.jpg',
    images: [
      '/images/projects/misyonbond.jpg',
      '/images/projects/misyonbond.jpg',
      '/images/projects/misyonbond.jpg',
    ],
    liveUrl: 'https://misyon.com/bond',
    featured: false,
    startDate: '2023-08',
  },
  {
    id: 'carrot-beta',
    title: 'Carrot BETA',
    description:
      'Web3-powered community engagement protocol rewarding on-chain actions with token incentives.',
    category: 'hackathon',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'Base'],
    coverImage: '/images/projects/carrot.png',
    githubUrl: 'https://github.com/huseyinium/carrot-beta',
    prize: 'ETHGlobal Cannes — Worldcoin Pool Prize',
    featured: false,
    endDate: '2025-07',
  },
  {
    id: 'swapzilla',
    title: 'SwapZilla',
    description: 'Cross-chain DEX aggregator with intent-based routing for optimal swap execution.',
    category: 'hackathon',
    stack: ['Solidity', 'React', '1inch', 'LayerZero'],
    coverImage: '/images/projects/swapzilla.png',
    images: [
      '/images/projects/swapzilla.png',
      '/images/projects/swapzilla.png',
      '/images/projects/swapzilla.png',
    ],
    prize: 'ETHGlobal Brussels — 1inch Pool Prize',
    featured: false,
    endDate: '2024-07',
  },
  {
    id: 'verifyworld',
    title: 'VerifyWorld',
    description:
      'Decentralized identity verification layer using World ID proofs for Sybil-resistant access.',
    category: 'hackathon',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'IPFS'],
    coverImage: '/images/projects/verifyworld.jpg',
    images: [
      '/images/projects/verifyworld.jpg',
      '/images/projects/verifyworld.jpg',
      '/images/projects/verifyworld.jpg',
    ],
    prize: 'ETHGlobal Istanbul — Worldcoin Pool Prize',
    featured: false,
    endDate: '2023-11',
  },
  {
    id: 'rent3',
    title: 'Rent3',
    description:
      'Web3-powered rental marketplace letting tenants pay rent with crypto and on-chain deposit escrow.',
    category: 'personal',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Viem',
      'wagmi',
      'zod',
      'Framer Motion',
      'NextAuth',
      'Lucide React',
      'TanStack React Query',
      'Prisma ORM',
      'NestJS',
      'Jest',
      'axios',
      'PostgreSQL',
      'PostCSS',
      'World ID SDK',
      'ESLint',
    ],
    coverImage: '/images/projects/rent3.jpg',
    images: [
      '/images/projects/rent3.jpg',
      '/images/projects/rent3.jpg',
      '/images/projects/rent3.jpg',
    ],
    featured: false,
    startDate: '2023-04',
  },
  {
    id: 'odtu-bdays',
    title: 'bdays.org',
    description:
      "Official website of ODTU Blockchain Days -- Turkiye's biggest blockchain event organized by a student community.",
    category: 'personal',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Resend',
      'React Hook Form',
      'Prisma ORM',
      'zod',
      'ESLint',
      'PostCSS',
      'Framer Motion',
      'Lucide React',
      'TanStack React Table',
      'Vercel',
      'Vercel DB',
      'PostgreSQL',
    ],
    coverImage: '/images/projects/bdaysorg.jpg',
    images: [
      '/images/projects/bdaysorg.jpg',
      '/images/projects/bdaysorg.jpg',
      '/images/projects/bdaysorg.jpg',
    ],
    featured: false,
    startDate: '2024-03',
  },
  {
    id: 'investbuddy',
    title: 'InvestBuddy',
    description:
      'Portfolio tracking and investment insight tool for early-stage retail investors in Turkey.',
    category: 'freelance',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'BABEL',
      'PostCSS',
      'wagmi',
      'Viem',
      'Redux Toolkit',
      'Lucide React',
      'GSAP',
      'TanStack React Query',
      'Chart.js',
    ],
    coverImage: '/images/projects/investbuddy.jpg',
    images: [
      '/images/projects/investbuddy.jpg',
      '/images/projects/investbuddy.jpg',
      '/images/projects/investbuddy.jpg',
    ],
    featured: false,
    startDate: '2023-02',
  },
  {
    id: 'type-i-fast',
    title: 'Type-i Fast',
    description: '10-finger typing speed training game.',
    category: 'personal',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'PostCSS'],
    coverImage: '/images/projects/type-i-fast.png',
    images: [
      '/images/projects/type-i-fast.png',
      '/images/projects/type-i-fast.png',
      '/images/projects/type-i-fast.png',
    ],
    featured: false,
    startDate: '',
  },
  {
    id: 'hushboard',
    title: 'Hushboard',
    description:
      'A macOS menu bar app that auto-mutes your microphone while you type, auto-unmutes when you stop.',
    category: 'personal',
    stack: ['Swift', 'xCode'],
    coverImage: 'https://img.youtube.com/vi/cGKs4567Th0/maxresdefault.jpg',
    isVideo: true,
    videoUrl: 'https://youtu.be/cGKs4567Th0',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'hilink',
    title: 'Hilink',
    description: '',
    category: 'personal',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'PostCSS', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'tic-tac-go',
    title: 'Tic-Tac-Go!',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Vite.js',
      'React',
      'JavaScript',
      'TailwindCSS',
      'PostCSS',
      'ESLint',
      'zod',
      'Lucide React',
      'Framer Motion',
      'Socket.io',
      'NodeJS',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'unreadme',
    title: 'unREADME',
    description: '',
    category: 'personal',
    stack: ['npm', 'TypeScript', 'Claude', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'gitpsycho',
    title: 'GitPsycho',
    description: '',
    category: 'personal',
    stack: ['npm', 'TypeScript', 'Claude', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'qr-manager',
    title: 'QR Manager',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'shadcn',
      'Framer Motion',
      'Resend',
      'zod',
      'Lucide React',
      'Prisma ORM',
      'Vercel DB',
      'PostgreSQL',
      'Vercel Analytics',
      'PostCSS',
      'ESLint',
      'React Hook Form',
      'TanStack React Query',
      'ESLint',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
  {
    id: 'fstack',
    title: 'fstack',
    description: '',
    category: 'personal',
    // DONE
    stack: ['npm', 'TypeScript', 'Claude API', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
  {
    id: 'detective',
    title: 'det(ective)',
    description: '',
    category: 'personal',
    // DONE
    stack: ['Python', 'NumPy', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
  {
    id: 'campus-arc-beta',
    title: 'Campus Arc BETA',
    description: '',
    category: 'hackathon',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Framer Motion',
      'Ethers',
      'Lucide React',
      'TanStack React Query',
      'ESLint',
      'Prisma ORM',
      'PostgreSQL',
      'Viem',
      'wagmi',
      'Open Campus ID SDK',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/campus-arc-beta.jpg',
    featured: false,
    startDate: '',
  },
  {
    id: 'campus-arc-mobile',
    title: 'Campus Arc Mobile',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Expo',
      'React Native',
      'TypeScript',
      'NativeWind',
      'TanStack React Query',
      'Clerk',
      'React Hook Form',
      'zod',
      'BABEL',
      'Lucide React Native',
      'AWS S3',
      'AWS RDS',
      'PostgreSQL',
      'AWS EC2',
      'ESLint',
      'axios',
      'Cursor',
      'Claude Code',
      'Git',
      'GitHub',
    ],
    coverImage: 'jpg',
    featured: false,
    startDate: '',
  },
  {
    id: 'portfolio',
    title: 'huseyinium.com',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'ESLint',
      'Resend',
      'Framer Motion',
      'Lucide React',
      'Three.js',
      'Magic UI',
      'React Bits',
      'Bun',
      'Claude Code',
      'Vercel',
      'Vercel OG',
      'Vercel Analytics',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
]
