/** Built-in icon keys render a lucide icon; the object form renders a custom image (e.g. an org's logo). */
export type AchievementIcon = 'trophy' | { image: string; alt: string }

export interface Achievement {
  icon: AchievementIcon
  tooltip: string
}

export interface Project {
  id: string
  title: string
  description: string
  longDescription?: string
  category: 'startup' | 'hackathon' | 'freelance' | 'open-source' | 'personal' | 'professional'
  stack: string[]
  coverImage: string
  liveUrl?: string
  githubUrl?: string
  /** Rendered as a trophy-icon achievement next to the title, tooltip = this text. */
  prize?: string
  /** Additional achievements (e.g. accelerator/program acceptances) shown next to the title. */
  achievements?: Achievement[]
  featured: boolean
  /** YYYY-MM, omit for single-date events (e.g. hackathons) — use endDate only */
  startDate?: string
  /** YYYY-MM, omit if ongoing */
  endDate?: string
  isVideo?: boolean
  videoUrl?: string
  images?: string[]
}

export const PROJECTS: Project[] = [
  {
    id: 'arcy-ai',
    title: 'ARCY AI',
    description: 'AI agent layer for B2B software products that prevents churn before it happens.',
    longDescription: '',
    category: 'startup',
    stack: [
      'Monorepo',
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'NestJS',
      'PostgreSQL',
      'npm',
      'AWS RDS',
      'AWS Bedrock',
      'AWS Bedrock Agentcore',
      'AWS EC2',
      'AWS IAM',
      'AWS Route53',
      'AWS SQS',
      'AWS Elastic Cache',
      'AWS CloudWatch',
      'Redis',
      'Git',
      'GitHub',
      'Claude Code',
      'ESLint',
      'PostCSS',
      'zod',
      'React Hook Form',
      'shadcn',
      'Stripe',
      'Clerk',
      'Framer Motion',
      'Lucide React',
      'Fumadocs',
      'i18n Translation',
    ],
    coverImage: '/images/projects/arcy-ai.jpg',
    images: [
      '/images/projects/arcy-ai.jpg',
      '/images/projects/arcy-ai.jpg',
      '/images/projects/arcy-ai.jpg',
    ],
    liveUrl: 'https://arcy.ai',
    achievements: [
      {
        icon: { image: '/logos/svg/nvidia.svg', alt: 'NVIDIA' },
        tooltip: 'Member of the NVIDIA Inception Program',
      },
      {
        icon: { image: '/logos/svg/founder-institute.svg', alt: 'Founder Institute' },
        tooltip: "Accepted to Founder Institute's Go Beyond Lab 2026",
      },
    ],
    featured: true,
    startDate: '2026-03',
  },
  {
    id: 'campus-arc',
    title: 'Campus Arc',
    description:
      'Campus ecosystem platform that connects students with carrer opportunities through events, clubs, and opportunities.',
    longDescription: '',
    category: 'startup',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Expo',
      'Express',
      'Node.js',
      'PostgreSQL',
      'Framer Motion',
      'zod',
      'ESLint',
      'Resend',
      'GSAP',
      'axios',
      'TanStack React Query',
      'Lucide React',
      'Clerk',
      'AWS S3',
      'AWS EC2',
      'PostCSS',
      'Open Campus ID SDK',
      'i18n Translation',
    ],
    coverImage: '/images/projects/campus-arc.jpg',
    images: [
      '/images/projects/campus-arc.jpg',
      '/images/projects/campus-arc.jpg',
      '/images/projects/campus-arc.jpg',
    ],
    achievements: [
      {
        icon: { image: '/logos/svg/odtu-teknokent.svg', alt: 'ODTÜ Teknokent' },
        tooltip: 'Accepted to ODTÜ Teknokent',
      },
      {
        icon: { image: '/logos/svg/open-campus.svg', alt: 'OC-I Cohort 1 graduation' },
        tooltip: 'Graduated from Open Campus Incubator Cohort 1 with $25,000 grant approved',
      },
      {
        icon: { image: '/logos/svg/founder-institute.svg', alt: 'Founder Institute' },
        tooltip: 'Accepted to Founder Institute',
      },
    ],
    featured: true,
    startDate: '2024-09',
    endDate: '2026-03',
  },
  {
    id: 'misyon-kripto',
    title: 'misyon.kripto',
    description:
      'The first product in Turkiye to let traditional investors access tokenized instruments with the regulatory assurance of conventional investment banking',
    category: 'professional',
    stack: [
      'Vite.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Prisma ORM',
      'Vercel',
      'PostCSS',
      'AWS S3',
      'Reown (WalletConnect)',
      'zod',
      'wagmi',
      'viem',
      'Resend',
      'Redux Toolkit',
      'Framer Motion',
      'Ethers.js',
      'Vercel Analytics',
      'Vercel DB',
      'Lucide React',
      'shadcn',
      'TanStack React Query',
      'TanStack React Table',
      'i18n Translation',
    ],
    coverImage: '/images/projects/misyon-kripto.jpg',
    images: [
      '/images/projects/misyon-kripto.jpg',
      '/images/projects/misyon-kripto.jpg',
      '/images/projects/misyon-kripto.jpg',
    ],
    liveUrl: 'https://misyon.com/kripto',
    achievements: [
      {
        icon: { image: '/logos/svg/misyon.svg', alt: 'Misyon Bank' },
        tooltip: 'PoC received board approval from Misyon Bank',
      },
      {
        icon: { image: '/logos/svg/spk.svg', alt: 'SPK' },
        tooltip: 'Received regulatory approval from SPK (Capital Markets Board of Türkiye)',
      },
      {
        icon: { image: '/logos/svg/inveo.svg', alt: 'Inveo' },
        tooltip: 'Acquired by Inveo Investment Holding and rebranded as Inveo Kripto',
      },
    ],
    featured: false,
    startDate: '2025-03',
    endDate: '2025-05',
  },
  {
    id: 'misyon-bond',
    title: 'misyon.bond',
    description:
      'Bond tokenization platform letting global investors access tokenized real-world assets in a few clicks.',
    longDescription: '',
    category: 'professional',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Prisma ORM',
      'Vercel',
      'PostCSS',
      'AWS S3',
      'Reown (WalletConnect)',
      'zod',
      'wagmi',
      'viem',
      'Resend',
      'Redux Toolkit',
      'Framer Motion',
      'Ethers.js',
      'Vercel Analytics',
      'Vercel DB',
      'Lucide React',
      'shadcn',
      'TanStack React Query',
      'TanStack React Table',
      'i18n Translation',
    ],
    coverImage: '/images/projects/misyonbond.jpg',
    images: [
      '/images/projects/misyonbond.jpg',
      '/images/projects/misyonbond.jpg',
      '/images/projects/misyonbond.jpg',
    ],
    liveUrl: 'https://misyon.com/bond',
    achievements: [
      {
        icon: { image: '/logos/svg/avalanche.svg', alt: 'Avalanche' },
        tooltip: 'In collaboration with Avalanche',
      },
      {
        icon: { image: '/logos/svg/taurus.svg', alt: 'Taurus' },
        tooltip: 'In collaboration with Taurus',
      },
      {
        icon: { image: '/logos/svg/bt-guru.svg', alt: 'bt.guru' },
        tooltip: 'In collaboration with bt.guru',
      },
      {
        icon: { image: '/logos/svg/amani-ai.svg', alt: 'Amani' },
        tooltip: 'In collaboration with Amani',
      },
      {
        icon: { image: '/logos/svg/acuris.svg', alt: 'Acuris' },
        tooltip: 'In collaboration with Acuris',
      },
      {
        icon: { image: '/logos/svg/xalts.svg', alt: 'X Alts' },
        tooltip: 'In collaboration with X Alts',
      },
      {
        icon: {
          image: '/logos/svg/blockchain-intelligence-group.svg',
          alt: 'Blockchain Intelligence Group',
        },
        tooltip: 'In collaboration with Blockchain Intelligence Group',
      },
    ],
    featured: false,
    startDate: '2024-01',
    endDate: '2025-01',
  },
  {
    id: 'carrot-beta',
    title: 'Carrot BETA',
    description: 'Web3-powered community engagement tools for blockchain companies.',
    category: 'hackathon',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'Base'],
    coverImage: '/images/projects/carrot.png',
    githubUrl: 'https://github.com/huseyinium/carrot-beta',
    prize: 'ETHGlobal Cannes — Worldcoin Pool Prize',
    featured: false,
    startDate: '2025-07',
    endDate: '2025-07',
  },
  {
    id: 'swapzilla',
    title: 'SwapZilla',
    description:
      'Blockscout pool-prize-winning dApp enabling cross-chain swaps via LayerZero without bridging assets.',
    category: 'hackathon',
    stack: ['Solidity', 'React', 'OneInch', 'LayerZero'],
    coverImage: '/images/projects/swapzilla.png',
    images: [
      '/images/projects/swapzilla.png',
      '/images/projects/swapzilla.png',
      '/images/projects/swapzilla.png',
    ],
    prize: 'ETHGlobal Brussels — OneInch Pool Prize',
    featured: false,
    startDate: '2024-07',
    endDate: '2024-07',
  },
  {
    id: 'verifyworld',
    title: 'VerifyWorld',
    description:
      'Blockchain-secured document signing dApp. World ID SDK for identity verification and IPFS storage.',
    category: 'hackathon',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'IPFS'],
    coverImage: '/images/projects/verifyworld.jpg',
    images: [
      '/images/projects/verifyworld.jpg',
      '/images/projects/verifyworld.jpg',
      '/images/projects/verifyworld.jpg',
    ],
    prize: 'ETHGlobal Istanbul — Worldcoin Pool Prize',
    featured: false,
    startDate: '2023-11',
    endDate: '2023-11',
  },
  {
    id: 'rent3',
    title: 'Rent3',
    description:
      'Decentralized rental platform providing secure, transparent rentals via Worldcoin and Blockscout.',
    category: 'personal',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Viem',
      'wagmi',
      'zod',
      'Framer Motion',
      'NextAuth',
      'Lucide React',
      'TanStack React Query',
      'Prisma ORM',
      'NestJS',
      'Jest',
      'axios',
      'PostgreSQL',
      'PostCSS',
      'World ID SDK',
      'ESLint',
    ],
    coverImage: '/images/projects/rent3.jpg',
    images: [
      '/images/projects/rent3.jpg',
      '/images/projects/rent3.jpg',
      '/images/projects/rent3.jpg',
    ],
    featured: false,
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'odtu-bdays',
    title: 'bdays.org',
    description: 'Official website of ODTÜ Blockchain Days 2024.',
    category: 'personal',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Resend',
      'React Hook Form',
      'Prisma ORM',
      'zod',
      'ESLint',
      'PostCSS',
      'Framer Motion',
      'Lucide React',
      'TanStack React Table',
      'Vercel',
      'Vercel DB',
      'PostgreSQL',
    ],
    coverImage: '/images/projects/bdaysorg.jpg',
    images: [
      '/images/projects/bdaysorg.jpg',
      '/images/projects/bdaysorg.jpg',
      '/images/projects/bdaysorg.jpg',
    ],
    featured: false,
    startDate: '2023-06',
    endDate: '2024-03',
  },
  {
    id: 'investbuddy',
    title: 'InvestBuddy',
    description:
      'Real-world asset tokenization web3 startup; PoC accepted to Cohort 2 of thirdweb.',
    category: 'freelance',
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'BABEL',
      'PostCSS',
      'wagmi',
      'Viem',
      'Redux Toolkit',
      'Lucide React',
      'GSAP',
      'TanStack React Query',
      'Chart.js',
    ],
    coverImage: '/images/projects/investbuddy.jpg',
    images: [
      '/images/projects/investbuddy.jpg',
      '/images/projects/investbuddy.jpg',
      '/images/projects/investbuddy.jpg',
    ],
    achievements: [
      {
        icon: { image: '/logos/svg/thirdweb.svg', alt: 'thirdweb' },
        tooltip: "Accepted to thirdweb's Accelerator Program (Cohort 2)",
      },
    ],
    featured: false,
    startDate: '2024-01',
    endDate: '2024-06',
  },
  {
    id: 'type-i-fast',
    title: 'Type-i Fast',
    description: 'A typing speed test game developed to practice 10-finger typing.',
    category: 'personal',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'PostCSS'],
    coverImage: '/images/projects/type-i-fast.png',
    images: [
      '/images/projects/type-i-fast.png',
      '/images/projects/type-i-fast.png',
      '/images/projects/type-i-fast.png',
    ],
    featured: false,
    startDate: '2023-11',
    endDate: '2024-02',
  },
  {
    id: 'hushboard',
    title: 'Hushboard',
    description:
      'A macOS menu bar app that auto-mutes your microphone while you type, auto-unmutes when you stop.',
    category: 'personal',
    stack: ['Swift', 'xCode'],
    coverImage: 'https://img.youtube.com/vi/cGKs4567Th0/maxresdefault.jpg',
    isVideo: true,
    videoUrl: 'https://youtu.be/cGKs4567Th0',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'hilink',
    title: 'Hilink',
    description: 'A fully responsive & modern UI/UX app of an imaginary travel agent.',
    category: 'personal',
    stack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'PostCSS', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2023-11',
    endDate: '2023-12',
  },
  {
    id: 'tic-tac-go',
    title: 'Tic-Tac-Go!',
    description:
      'A web-based, multiplayer Tic-Tac-Toe game with configurable grid size, per-player time limits, and round counts. (Not finished)',
    category: 'personal',
    // DONE
    stack: [
      'Vite.js',
      'React',
      'JavaScript',
      'TailwindCSS',
      'PostCSS',
      'ESLint',
      'zod',
      'Lucide React',
      'Framer Motion',
      'Socket.io',
      'NodeJS',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2024-07',
    endDate: '2024-09',
  },
  {
    id: 'unreadme',
    title: 'unREADME',
    description: '',
    category: 'personal',
    stack: ['npm', 'TypeScript', 'Claude', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'gitpsycho',
    title: 'GitPsycho',
    description: '',
    category: 'personal',
    stack: ['npm', 'TypeScript', 'Claude', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2026-04',
  },
  {
    id: 'qr-manager',
    title: 'QR Manager',
    description:
      'Event management tool for GDSC METU enabling quick QR check-ins and automated follow-up email notifications.',
    category: 'personal',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'shadcn',
      'Framer Motion',
      'Resend',
      'zod',
      'Lucide React',
      'Prisma ORM',
      'Vercel DB',
      'PostgreSQL',
      'Vercel Analytics',
      'PostCSS',
      'ESLint',
      'React Hook Form',
      'TanStack React Query',
      'ESLint',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'fstack',
    title: 'fstack',
    description: '',
    category: 'personal',
    // DONE
    stack: ['npm', 'TypeScript', 'Claude API', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
  {
    id: 'detective',
    title: 'det(ective)',
    description:
      'A Python program that calculates the determinant of square matrices of any size recursively.',
    category: 'personal',
    // DONE
    stack: ['Python', 'NumPy', 'Git', 'GitHub'],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '2023-11',
    endDate: '2023-11',
  },
  {
    id: 'campus-arc-beta',
    title: 'Campus Arc BETA',
    description: 'Rank #1 winner in the EduFi category at the EDU Chain Hackathon.',
    category: 'hackathon',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'Framer Motion',
      'Ethers',
      'Lucide React',
      'TanStack React Query',
      'ESLint',
      'Prisma ORM',
      'PostgreSQL',
      'Viem',
      'wagmi',
      'Open Campus ID SDK',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/campus-arc-beta.jpg',
    featured: false,
    prize: 'EDU Chain Hackathon — EduFi Category, Rank #1',
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'campus-arc-mobile',
    title: 'Campus Arc Mobile',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Expo',
      'React Native',
      'TypeScript',
      'NativeWind',
      'TanStack React Query',
      'Clerk',
      'React Hook Form',
      'zod',
      'BABEL',
      'Lucide React Native',
      'AWS S3',
      'AWS RDS',
      'PostgreSQL',
      'AWS EC2',
      'ESLint',
      'axios',
      'Cursor',
      'Claude Code',
      'Git',
      'GitHub',
    ],
    coverImage: 'jpg',
    featured: false,
    startDate: '',
  },
  {
    id: 'portfolio',
    title: 'huseyinium.com',
    description: '',
    category: 'personal',
    // DONE
    stack: [
      'Next.js',
      'React',
      'TypeScript',
      'TailwindCSS',
      'ESLint',
      'Resend',
      'Framer Motion',
      'Lucide React',
      'Three.js',
      'Magic UI',
      'React Bits',
      'Bun',
      'Claude Code',
      'Vercel',
      'Vercel OG',
      'Vercel Analytics',
      'Git',
      'GitHub',
    ],
    coverImage: '/images/projects/',
    featured: false,
    startDate: '',
  },
]
