/** Built-in icon keys render a lucide icon; the object form renders a custom image (e.g. an org's logo). */
export type AchievementIcon = 'trophy' | { image: string; alt: string }

export interface Achievement {
  icon: AchievementIcon
  tooltip: string
}

export type ProjectScope = 'Full-Stack' | 'Frontend' | 'Backend' | 'Mobile' | 'Desktop'

export interface Project {
  id: string
  title: string
  description: string
  longDescription?: string
  category:
    | 'startup'
    | 'hackathon'
    | 'freelance'
    | 'open-source'
    | 'personal'
    | 'professional'
    | 'personal-case-study'
  scope: ProjectScope
  stack: string[]
  coverImage: string
  websiteUrl?: string
  liveDemoUrl?: string
  githubUrl?: string
  appStoreUrl?: string
  googlePlayUrl?: string
  /** Rendered as a trophy-icon achievement next to the title, tooltip = this text. */
  prize?: string
  /** Additional achievements (e.g. accelerator/program acceptances) shown next to the title. */
  achievements?: Achievement[]
  featured: boolean
  /** YYYY-MM, omit for single-date events (e.g. hackathons) — use endDate only */
  startDate?: string
  /** YYYY-MM, omit if ongoing */
  endDate?: string
  isVideo?: boolean
  videoUrl?: string
  images?: string[]
}

export const PROJECTS: Project[] = [
  {
    id: 'gitpsycho',
    title: 'GitPsycho',
    description:
      'A CLI tool that gives a "psychological profile" of a GitHub repository based on its commit history.',
    category: 'personal',
    scope: 'Backend',
    stack: [
      'TypeScript',
      'Claude API',
      'Claude Code',
      "Garry Tan's gstack",
      'Git',
      'GitHub',
      'npm',
    ],
    coverImage: '/images/projects/gitpsycho.png',
    websiteUrl: '',
    githubUrl: '',
    featured: false,
    startDate: '2026-06',
  },
  {
    id: 'fstack',
    title: 'fstack',
    description:
      'Claude Code skill suite that lets non-technical founders load persistent company context into tools.',
    category: 'personal',
    scope: 'Backend',
    // DONE
    stack: [
      'TypeScript',
      'Claude API',
      'Claude Code',
      "Garry Tan's gstack",
      'Git',
      'GitHub',
      'npm',
    ],
    coverImage: '/images/projects/fstack.png',
    websiteUrl: '',
    githubUrl: '',
    featured: false,
    startDate: '2026-06',
  },
  {
    id: 'arcy-ai',
    title: 'ARCY AI',
    description: 'AI agent layer for B2B software products that prevents churn before it happens.',
    longDescription: '',
    category: 'startup',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'NestJS',
      'TailwindCSS',
      'shadcn',
      'Framer Motion',
      'Lucide React',
      'zod',
      'React Hook Form',
      'Clerk',
      'PostgreSQL',
      'Redis',
      'Claude Code',
      "Garry Tan's gstack",
      'Monorepo',
      'AWS RDS',
      'AWS Bedrock',
      'AWS Bedrock Agentcore',
      'AWS EC2',
      'AWS IAM',
      'AWS Route53',
      'AWS SQS',
      'AWS Elastic Cache',
      'AWS CloudWatch',
      'Stripe',
      'Fumadocs',
      'i18n Translation',
      'Git',
      'GitHub',
      'npm',
      'ESLint',
      'PostCSS',
    ],
    coverImage: '/images/projects/arcy-ai.jpg',
    githubUrl: '',
    websiteUrl: 'https://arcy.ai',
    liveDemoUrl: 'https://demo.arcyai.com',
    achievements: [
      {
        icon: { image: '/logos/svg/nvidia.svg', alt: 'NVIDIA' },
        tooltip: 'Member of the NVIDIA Inception Program',
      },
      {
        icon: { image: '/logos/svg/founder-institute.svg', alt: 'Founder Institute' },
        tooltip: "Accepted to Founder Institute's Go Beyond Lab 2026",
      },
    ],
    featured: true,
    startDate: '2026-04',
  },
  {
    id: 'portfolio',
    title: 'huseyinium.com',
    description:
      'My personal portfolio: projects, skills, experience, achievements, and a way to reach me.',
    category: 'personal',
    scope: 'Full-Stack',
    // DONE
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'TailwindCSS',
      'Framer Motion',
      'Three.js',
      'Magic UI',
      'React Bits',
      'Lucide React',
      'Claude Code',
      'Vercel',
      'Vercel OG',
      'Vercel Analytics',
      'Resend',
      'Git',
      'GitHub',
      'Bun',
      'ESLint',
    ],
    coverImage: '/images/projects/huseyinium.jpg',
    websiteUrl: 'https://huseyinium.com',
    githubUrl: 'https://github.com/huseyinium/huseyinium.com',
    featured: false,
    startDate: '2026-06',
    endDate: '2026-06',
  },
  {
    id: 'hushboard',
    title: 'Hushboard',
    description:
      'A macOS menu bar app that auto-mutes your microphone while you type, auto-unmutes when you stop.',
    category: 'personal',
    scope: 'Desktop',
    stack: ['Swift', 'Claude Code', 'xCode'],
    coverImage: 'https://img.youtube.com/vi/cGKs4567Th0/maxresdefault.jpg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/hushboard',
    isVideo: true,
    videoUrl: 'https://youtu.be/cGKs4567Th0',
    featured: false,
    startDate: '2026-04',
    endDate: '2026-04',
  },
  {
    id: 'unreadme',
    title: 'unREADME',
    description: 'An npm package to generate great READMEs with just one command.',
    category: 'personal',
    scope: 'Backend',
    stack: [
      'TypeScript',
      'Claude API',
      'Claude Code',
      "Garry Tan's gstack",
      'Git',
      'GitHub',
      'npm',
    ],
    coverImage: '/images/projects/unreadme.jpg',
    websiteUrl: 'https://www.npmjs.com/unreadme',
    githubUrl: 'https://github.com/huseyinium/unREADME',
    featured: false,
    startDate: '2026-04',
    endDate: '2026-04',
  },
  {
    id: 'campus-arc',
    title: 'Campus Arc',
    description:
      'Campus ecosystem platform that connects students with carrer opportunities through events, clubs, and hackathons.',
    longDescription: '',
    category: 'startup',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'Expo',
      'Express',
      'Node.js',
      'TailwindCSS',
      'Framer Motion',
      'GSAP',
      'Lucide React',
      'zod',
      'TanStack React Query',
      'axios',
      'Open Campus ID SDK',
      'Clerk',
      'PostgreSQL',
      'Claude Code',
      'Gemini API',
      'AWS EC2',
      'AWS S3',
      'Resend',
      'i18n Translation',
      'ESLint',
      'Cursor',
      'PostCSS',
    ],
    coverImage: '/images/projects/campus-arc.jpg',
    websiteUrl: 'https://campusarc.com',
    githubUrl: '',
    achievements: [
      {
        icon: { image: '/logos/svg/odtu-teknokent.svg', alt: 'ODTÜ Teknokent' },
        tooltip: 'Accepted to ODTÜ Teknokent',
      },
      {
        icon: { image: '/logos/svg/open-campus.svg', alt: 'OC-I Cohort 1 graduation' },
        tooltip: 'Graduated from Open Campus Incubator Cohort 1 with $25,000 grant approved',
      },
      {
        icon: { image: '/logos/svg/founder-institute.svg', alt: 'Founder Institute' },
        tooltip: 'Accepted to Founder Institute',
      },
    ],
    featured: true,
    startDate: '2024-09',
    endDate: '2026-04',
  },
  {
    id: 'campus-arc-mobile',
    title: 'Campus Arc Mobile',
    description: 'iOS and Android apps of Campus Arc.',
    category: 'startup',
    scope: 'Mobile',
    // DONE
    stack: [
      'TypeScript',
      'React Native',
      'Expo',
      'NativeWind',
      'Lucide React Native',
      'zod',
      'React Hook Form',
      'TanStack React Query',
      'axios',
      'Clerk',
      'PostgreSQL',
      'Claude Code',
      'AWS RDS',
      'AWS EC2',
      'AWS S3',
      'Git',
      'GitHub',
      'ESLint',
      'BABEL',
      'Cursor',
    ],
    coverImage: '/images/projects/campus-arc-mobile.png',
    websiteUrl: '',
    githubUrl: '',
    appStoreUrl: 'https://apps.apple.com/tr/app/campus-arc/id6755310766',
    googlePlayUrl: 'https://play.google.com/store/apps/details?id=com.campusarc.mobile.earlyaccess',
    featured: false,
    startDate: '2025-10',
    endDate: '2026-03',
  },
  {
    id: 'carrot-beta',
    title: 'Carrot BETA',
    description: 'Web3-powered community engagement tools for blockchain companies.',
    category: 'hackathon',
    scope: 'Full-Stack',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'Base'],
    coverImage: '/images/projects/carrot.png',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/carrot-beta',
    prize: 'ETHGlobal Cannes 2025 — Worldcoin Pool Prize',
    featured: false,
    startDate: '2025-07',
    endDate: '2025-07',
  },
  {
    id: 'misyon-kripto',
    title: 'Misyon Kripto',
    description:
      'The first product in Turkiye to let traditional investors access tokenized instruments with the regulatory assurance of conventional investment banking.',
    category: 'professional',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'React',
      'Vite.js',
      'Tailwind CSS',
      'shadcn',
      'Redux Toolkit',
      'Framer Motion',
      'Lucide React',
      'zod',
      'TanStack React Query',
      'TanStack React Table',
      'wagmi',
      'viem',
      'Ethers.js',
      'Reown (WalletConnect)',
      'Prisma ORM',
      'AWS S3',
      'Vercel',
      'Vercel Analytics',
      'Vercel DB',
      'Resend',
      'i18n Translation',
      'PostCSS',
    ],
    coverImage: '/images/projects/misyon-kripto.jpg',
    githubUrl: '',
    websiteUrl: 'https://inveokripto.com/',
    achievements: [
      {
        icon: { image: '/logos/svg/misyon.svg', alt: 'Misyon Bank' },
        tooltip: 'PoC received board approval from Misyon Bank',
      },
      {
        icon: { image: '/logos/svg/spk.svg', alt: 'SPK' },
        tooltip: 'Received regulatory approval from SPK (Capital Markets Board of Türkiye)',
      },
      {
        icon: { image: '/logos/svg/inveo.svg', alt: 'Inveo' },
        tooltip: 'Acquired by Inveo Investment Holding and rebranded as Inveo Kripto',
      },
    ],
    featured: false,
    startDate: '2025-03',
    endDate: '2025-05',
  },
  {
    id: 'misyon-bond',
    title: 'Misyon Bond',
    description:
      'Bond tokenization platform letting global investors access tokenized real-world assets in a few clicks.',
    longDescription: '',
    category: 'professional',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'Tailwind CSS',
      'shadcn',
      'Redux Toolkit',
      'Framer Motion',
      'Lucide React',
      'zod',
      'TanStack React Query',
      'TanStack React Table',
      'wagmi',
      'viem',
      'Ethers.js',
      'Reown (WalletConnect)',
      'Prisma ORM',
      'AWS S3',
      'Vercel',
      'Vercel Analytics',
      'Vercel DB',
      'Resend',
      'i18n Translation',
      'Cursor',
      'PostCSS',
    ],
    coverImage: '/images/projects/misyonbond.jpg',
    githubUrl: '',
    websiteUrl: '',
    achievements: [
      {
        icon: { image: '/logos/svg/avalanche.svg', alt: 'Avalanche' },
        tooltip: 'In collaboration with Avalanche',
      },
      {
        icon: { image: '/logos/svg/taurus.svg', alt: 'Taurus' },
        tooltip: 'In collaboration with Taurus',
      },
      {
        icon: { image: '/logos/svg/bt-guru.svg', alt: 'bt.guru' },
        tooltip: 'In collaboration with bt.guru',
      },
      {
        icon: { image: '/logos/svg/amani-ai.svg', alt: 'Amani' },
        tooltip: 'In collaboration with Amani',
      },
      {
        icon: { image: '/logos/svg/acuris.svg', alt: 'Acuris' },
        tooltip: 'In collaboration with Acuris',
      },
      {
        icon: { image: '/logos/svg/xalts.svg', alt: 'X Alts' },
        tooltip: 'In collaboration with X Alts',
      },
      {
        icon: {
          image: '/logos/svg/blockchain-intelligence-group.svg',
          alt: 'Blockchain Intelligence Group',
        },
        tooltip: 'In collaboration with Blockchain Intelligence Group',
      },
    ],
    featured: false,
    startDate: '2024-01',
    endDate: '2025-01',
  },
  {
    id: 'tic-tac-go',
    title: 'Tic-Tac-Go!',
    description:
      'A web-based, multiplayer Tic-Tac-Toe game with configurable grid size, per-player time limits, and round counts. (Not finished)',
    category: 'personal',
    scope: 'Full-Stack',
    // DONE
    stack: [
      'JavaScript',
      'React',
      'Vite.js',
      'NodeJS',
      'Socket.io',
      'TailwindCSS',
      'Framer Motion',
      'Lucide React',
      'zod',
      'ChatGPT',
      'Git',
      'GitHub',
      'ESLint',
      'PostCSS',
    ],
    coverImage: '/images/projects/tic-tac-go-1.jpg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/tic-tac-go',
    images: [
      '/images/projects/tic-tac-go-1.jpg',
      '/images/projects/tic-tac-go-2.jpg',
      '/images/projects/tic-tac-go-3.jpg',
      '/images/projects/tic-tac-go-4.jpg',
      '/images/projects/tic-tac-go-5.jpg',
    ],
    featured: false,
    startDate: '2024-07',
    endDate: '2024-09',
  },
  {
    id: 'rent3',
    title: 'Rent3',
    description:
      'Decentralized rental platform providing secure, transparent rentals via Worldcoin and Blockscout.',
    category: 'personal',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'NestJS',
      'TailwindCSS',
      'Framer Motion',
      'Lucide React',
      'zod',
      'TanStack React Query',
      'axios',
      'wagmi',
      'Viem',
      'World ID SDK',
      'NextAuth',
      'PostgreSQL',
      'Prisma ORM',
      'ESLint',
      'Jest',
      'PostCSS',
    ],
    coverImage: '/images/projects/rent3-1.jpg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/Rent3-ETHGlobal-Superhack2024-Hackaton',
    images: [
      '/images/projects/rent3-1.jpg',
      '/images/projects/rent3-2.jpeg',
      '/images/projects/rent3-3.jpeg',
    ],
    prize: 'ETHGlobal Superchain 2024 — Blockscout Pool Prize',
    featured: false,
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'qr-manager',
    title: 'QR Manager',
    description:
      'Event management tool for GDSC METU enabling quick QR check-ins and automated follow-up email notifications.',
    category: 'personal',
    scope: 'Full-Stack',
    // DONE
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'TailwindCSS',
      'shadcn',
      'Framer Motion',
      'Lucide React',
      'zod',
      'React Hook Form',
      'TanStack React Query',
      'PostgreSQL',
      'Prisma ORM',
      'Vercel Analytics',
      'Vercel DB',
      'Resend',
      'Git',
      'GitHub',
      'ESLint',
      'ESLint',
      'PostCSS',
    ],
    coverImage: '/images/projects/qr-manager.png',
    websiteUrl: '',
    githubUrl: '',
    featured: false,
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'campus-arc-beta',
    title: 'Campus Arc BETA',
    description: 'An e-learning platform that enables earning while leaning, built on EDUChain.',
    category: 'hackathon',
    scope: 'Full-Stack',
    // DONE
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'TailwindCSS',
      'Framer Motion',
      'Lucide React',
      'TanStack React Query',
      'wagmi',
      'Viem',
      'Ethers',
      'Open Campus ID SDK',
      'PostgreSQL',
      'Prisma ORM',
      'Git',
      'GitHub',
      'ESLint',
    ],
    coverImage: '/images/projects/campus-arc-beta.jpg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/Campus-Arc-BETA',
    featured: false,
    prize: 'EDU Chain Hackathon Semester 1 — Rank #1, EduFi Category',
    startDate: '2024-08',
    endDate: '2024-08',
  },
  {
    id: 'swapzilla',
    title: 'SwapZilla',
    description:
      'A decentralized application that enables cross-chain swaps via LayerZero without bridging assets.',
    category: 'hackathon',
    scope: 'Full-Stack',
    stack: ['Solidity', 'React', 'OneInch', 'LayerZero'],
    coverImage: '/images/projects/swapzilla-1.png',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/SwapZilla-ETHGlobal-Brussels2024-Hackaton',
    images: [
      '/images/projects/swapzilla-1.png',
      '/images/projects/swapzilla-2.png',
      '/images/projects/swapzilla-3.png',
      '/images/projects/swapzilla-4.png',
    ],
    prize: 'ETHGlobal Brussels 2024 — OneInch Pool Prize',
    featured: false,
    startDate: '2024-07',
    endDate: '2024-07',
  },
  {
    id: 'investbuddy',
    title: 'InvestBuddy',
    description: 'Proof of Concept of Real-World Asset (RWA) tokenization web3 startup.',
    category: 'freelance',
    scope: 'Frontend',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'TailwindCSS',
      'Redux Toolkit',
      'GSAP',
      'Chart.js',
      'Lucide React',
      'TanStack React Query',
      'wagmi',
      'Viem',
      'BABEL',
      'PostCSS',
    ],
    coverImage: '/images/projects/investbuddy-0.jpg',
    websiteUrl: '',
    githubUrl: '',
    images: [
      '/images/projects/investbuddy-0.jpg',
      '/images/projects/investbuddy-1.jpg',
      '/images/projects/investbuddy-2.jpg',
      '/images/projects/investbuddy-3.jpg',
    ],
    achievements: [
      {
        icon: { image: '/logos/svg/thirdweb.svg', alt: 'thirdweb' },
        tooltip: "Accepted to thirdweb's Accelerator Program (Cohort 2)",
      },
    ],
    featured: false,
    startDate: '2024-01',
    endDate: '2024-06',
  },
  {
    id: 'odtu-bdays',
    title: 'bdays.org',
    description: 'Official website of ODTÜ Blockchain Days 2024.',
    category: 'personal',
    scope: 'Full-Stack',
    stack: [
      'TypeScript',
      'Next.js',
      'React',
      'TailwindCSS',
      'Framer Motion',
      'Lucide React',
      'zod',
      'React Hook Form',
      'TanStack React Table',
      'PostgreSQL',
      'Prisma ORM',
      'Vercel',
      'Vercel DB',
      'Resend',
      'ESLint',
      'PostCSS',
    ],
    coverImage: '/images/projects/bdaysorg.jpg',
    websiteUrl: 'https://bdays.org',
    githubUrl: '',
    featured: false,
    startDate: '2023-06',
    endDate: '2024-03',
  },
  {
    id: 'type-i-fast',
    title: 'Type-i Fast',
    description: 'A typing speed test game developed to practice 10-finger typing.',
    category: 'personal',
    scope: 'Frontend',
    stack: ['TypeScript', 'Next.js', 'React', 'TailwindCSS', 'Framer Motion', 'PostCSS'],
    coverImage: '/images/projects/type-i-fast-1.jpeg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/Type-i-Fast',
    images: ['/images/projects/type-i-fast-1.jpeg', '/images/projects/type-i-fast-2.jpeg'],
    featured: false,
    startDate: '2023-11',
    endDate: '2024-02',
  },
  {
    id: 'hilink',
    title: 'Hilink',
    description: 'A fully responsive & modern UI/UX app of an imaginary travel agent.',
    category: 'personal-case-study',
    scope: 'Frontend',
    stack: ['TypeScript', 'Next.js', 'React', 'TailwindCSS', 'Git', 'GitHub', 'PostCSS'],
    coverImage: '/images/projects/hilink-1.png',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/hilink',
    images: [
      '/images/projects/hilink-1.png',
      '/images/projects/hilink-2.png',
      '/images/projects/hilink-3.png',
      '/images/projects/hilink-4.png',
      '/images/projects/hilink-5.png',
    ],
    featured: false,
    startDate: '2023-11',
    endDate: '2023-12',
  },
  {
    id: 'verifyworld',
    title: 'VerifyWorld',
    description:
      'Blockchain-secured document signing dApp. World ID SDK for identity verification and IPFS storage.',
    category: 'hackathon',
    scope: 'Full-Stack',
    stack: ['Solidity', 'Next.js', 'World ID SDK', 'IPFS'],
    coverImage: '/images/projects/verifyworld.jpg',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/VerifyWorld-ETHGlobal-Istanbul2023-Hackaton',
    prize: 'ETHGlobal Istanbul 2023 — Worldcoin Pool Prize',
    featured: false,
    startDate: '2023-11',
    endDate: '2023-11',
  },
  {
    id: 'detective',
    title: 'det(ective)',
    description:
      'A Python program that calculates the determinant of square matrices of any size recursively.',
    category: 'personal',
    scope: 'Backend',
    // DONE
    stack: ['Python', 'NumPy', 'ChatGPT', 'Git', 'GitHub'],
    coverImage: '/images/projects/detective.png',
    websiteUrl: '',
    githubUrl: 'https://github.com/huseyinium/det-ective',
    featured: false,
    startDate: '2023-11',
    endDate: '2023-11',
  },
]
