import { codeToHtml } from 'shiki'

interface Props {
  code: string
  lang?: string
}

// Safe: HTML is generated by Shiki from static code strings, never from user input.
export async function CodeBlock({ code, lang = 'text' }: Props) {
  const html = await codeToHtml(code.trim(), {
    lang,
    theme: 'github-dark',
  })

  return (
    <div
      className="my-6 rounded-xl overflow-hidden text-sm font-mono"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
