export const TECH_LOGOS: Record<string, string> = {
  // AWS
  'amazon web services': '/logos/svg/amazon-web-services.svg',
  aws: '/logos/svg/amazon-web-services.svg',
  'aws amplify': '/logos/svg/aws-amplify.svg',
  'aws bedrock agentcore': '/logos/svg/aws-bedrock-agentcore.svg',
  'bedrock agentcore': '/logos/svg/aws-bedrock-agentcore.svg',
  'aws cloudfront': '/logos/svg/aws-cloudfront.svg',
  cloudfront: '/logos/svg/aws-cloudfront.svg',
  'aws cloudwatch': '/logos/svg/aws-cloudwatch.svg',
  cloudwatch: '/logos/svg/aws-cloudwatch.svg',
  'aws ec2': '/logos/svg/aws-ec2.svg',
  ec2: '/logos/svg/aws-ec2.svg',
  'aws elasticache': '/logos/svg/aws-elastic-cache.svg',
  elasticache: '/logos/svg/aws-elastic-cache.svg',
  'aws iam': '/logos/svg/aws-iam.svg',
  iam: '/logos/svg/aws-iam.svg',
  'aws lambda': '/logos/svg/aws-lambda.svg',
  lambda: '/logos/svg/aws-lambda.svg',
  'aws rds': '/logos/svg/aws-rds.svg',
  rds: '/logos/svg/aws-rds.svg',
  'aws route 53': '/logos/svg/aws-route-53.svg',
  'route 53': '/logos/svg/aws-route-53.svg',
  'aws s3': '/logos/svg/aws-s3.svg',
  s3: '/logos/svg/aws-s3.svg',
  'aws sqs': '/logos/svg/aws-sqs.svg',
  sqs: '/logos/svg/aws-sqs.svg',

  // Languages & runtimes
  typescript: '/logos/svg/typescript.svg',
  javascript: '/logos/svg/javascript.svg',
  js: '/logos/svg/javascript.svg',
  python: '/logos/svg/python.svg',
  php: '/logos/svg/php.svg',
  bun: '/logos/svg/bun.svg',
  'node.js': '/logos/svg/nodejs.svg',
  nodejs: '/logos/svg/nodejs.svg',

  // Frontend
  react: '/logos/svg/react.svg',
  'react native': '/logos/svg/react.svg',
  'next.js': '/logos/svg/nextjs.svg',
  nextjs: '/logos/svg/nextjs.svg',
  'tailwind css': '/logos/svg/tailwind-css.svg',
  tailwindcss: '/logos/svg/tailwind-css.svg',
  nativewind: '/logos/svg/nativewind.svg',
  css: '/logos/svg/css.svg',
  css3: '/logos/svg/css.svg',
  bootstrap: '/logos/svg/bootstrap.svg',
  redux: '/logos/svg/redux.svg',
  'chart.js': '/logos/svg/chartjs.svg',
  'redux toolkit': '/logos/svg/redux.svg',
  gsap: '/logos/svg/gsap.svg',
  'shadcn/ui': '/logos/svg/shadcn.svg',
  shadcn: '/logos/svg/shadcn.svg',
  vite: '/logos/svg/vitejs.svg',
  'vite.js': '/logos/svg/vitejs.svg',
  expo: '/logos/svg/expo.svg',
  livewire: '/logos/svg/livewire.svg',
  'laravel (php)': '/logos/svg/laravel%201.svg',
  laravel: '/logos/svg/laravel%201.svg',
  tanstack: '/logos/svg/tanstack.svg',
  'tanstack react query': '/logos/svg/tanstack.svg',
  'tanstack react table': '/logos/svg/tanstack.svg',

  // Backend & data
  nestjs: '/logos/svg/nestjs.svg',
  express: '/logos/svg/express.svg',
  'express.js': '/logos/svg/express.svg',
  postgresql: '/logos/svg/postgresql.svg',
  postgres: '/logos/svg/postgresql.svg',
  prisma: '/logos/svg/prisma-orm.svg',
  'prisma orm': '/logos/svg/prisma-orm.svg',
  redis: '/logos/svg/redis.svg',
  nginx: '/logos/svg/nginx.svg',
  apache: '/logos/svg/apache.svg',
  numpy: '/logos/svg/numpy.svg',
  'socket.io': '/logos/svg/socketio.svg',
  socketio: '/logos/svg/socketio.svg',
  nextauth: '/logos/svg/nextauth.svg',
  firebase: '/logos/svg/firebase.svg',

  // AI
  openai: '/logos/svg/openai.svg',
  claude: '/logos/svg/claude.svg',
  'claude code': '/logos/svg/claude-code.svg',
  'claude api': '/logos/svg/claude.svg',

  // Tooling & infra
  docker: '/logos/svg/docker.svg',
  vercel: '/logos/svg/vercel.svg',
  'vercel db': '/logos/svg/vercel.svg',
  'vercel og': '/logos/svg/vercel.svg',
  'vercel analytics': '/logos/svg/vercel.svg',
  git: '/logos/svg/git.svg',
  github: '/logos/svg/github.svg',
  eslint: '/logos/svg/eslint.svg',
  babel: '/logos/svg/babel.svg',
  jest: '/logos/svg/jest.svg',
  postman: '/logos/svg/postman.svg',
  figma: '/logos/svg/figma.svg',
  xcode: '/logos/svg/xcode.svg',
  stripe: '/logos/svg/stripe.svg',
  resend: '/logos/svg/resend.svg',
  swift: '/logos/svg/swift.svg',
  'lucide react': '/logos/svg/lucide-react.svg',
  'lucide react native': '/logos/svg/lucide-react.svg',
  zod: '/logos/svg/zod.svg',
  'react hook form': '/logos/svg/react-hook-form.svg',
  gemini: '/logos/svg/gemini.svg',
  'google maps': '/logos/svg/google-maps.svg',
  clerk: '/logos/svg/clerk.svg',
  cursor: '/logos/svg/cursor.svg',
  viem: '/logos/svg/viem.svg',
  ethersjs: '/logos/svg/ethersjs.svg',
  wagmi: '/logos/svg/wagmi.svg',
  postcss: '/logos/svg/postcss.svg',
  threejs: '/logos/svg/threejs.svg',
  magicui: '/logos/svg/magic-ui.svg',
  'react bits': '/logos/svg/react-bits.svg',
  monorepo: '/logos/svg/monorepo.svg',
  fumadocs: '/logos/svg/fumadocs.svg',
  'open campus id sdk': '/logos/svg/open-campus.svg',
  'framer motion': '/logos/svg/framer-motion.svg',
  'i18n translation': '/logos/svg/i18n.svg',
  'world id sdk': '/logos/svg/worldcoin.svg',
  base: '/logos/svg/base.svg',
  solidity: '/logos/svg/solidity.svg',
  npm: '/logos/svg/npm.svg',
}

export function techLogo(tech: string) {
  return TECH_LOGOS[tech.toLowerCase()]
}
